apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sample.fullname" . }}
data:
  myvalue: "Hello World"
  SOME_URL: https://www.google.com
  SOME_PARAM: "Rahul"
  SOME_FILE: /config/game.properties
  TEST_PARAM: "Value"
