name: GitHub Utilities Workflow

on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: my-runners
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - name: "Calling GitHub Repo Creation Composite Action"
        uses: ./.github/actions/github-action/repo/create
        with:
          repo_name: 'sample-repo-from-action'
          repo_description: 'Sample repository created from composite action'
          is_private: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Primary setup job â€” other jobs will `need` this one