name: GitHub Utilities Workflow

on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: my-runners
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - name: "Calling GitHub Repo Creation Composite Action"
        uses: ./.github/modules/create-repo.yml
        with:
          repo-name: 'sample-repo-from-action'
          private: false

  # Primary setup job â€” other jobs will `need` this one