name: Podman CI

on:
  push:
    branches: [ master ]

jobs:
  podman-job:
    runs-on: my-runners

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman


      - name: Verify Podman installation
        run: podman info

      - name: Build container image
        run: podman build -t myapp .

      - name: Run container
        run: podman run --rm myapp
