name: Cat File Example

on:
  workflow_dispatch:

jobs:
  show-file:
    runs-on: my-runners

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Go to folder and cat file
        run: |
          cd jenkins
          cat values.yaml
