name: Podman Runner Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: podman-runners
    steps:
      - run: |
         echo "âœ… Podman runner is working"
         podman info
         podman --version
         podman pull alpine
         podman build -t my-alpine-image - <<EOF
           FROM alpine
           CMD ["echo", "Hello from Podman container!"]
           EOF
         podman run --rm my-alpine-image
         echo "ðŸš€ Podman container ran successfully"

