name: run podman inside runner

on:
  push:
    branches:
      - master

jobs:
  show-file:
    runs-on: podman-runner-scale-set

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: get podman version
        run: |
          podman version
      - name: list podman containers
        run: |
          podman ps -a
      - name: pull alpine image
        run: |
          podman pull alpine:latest