name: Scheduled CI Job

on:
  schedule:
    # Runs at 1:30 AM UTC every day
    - cron: '*/5 * * * *'
  workflow_dispatch: # Optional: allows manual trigger

jobs:
  run-scheduled-task:
    runs-on: podman-runners
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run script
        run: |
          echo "This workflow runs on a schedule, just like a Jenkins cron job."
          date
